### ISSUE TITLE
Reading value of variable fails after some number of requests

### ISSUE THREAD

**Issue by wdimmit** [Brewskey/spark-server#59]
If I repeat a get request to /v1/devices/{deviceid}/{varname} every 1 second, the server stops returning the variable's value and starts returning `{"error":"\"value\" argument is out of bounds","ok":false}` instead in under 5 minutes.  

This error only impacts the device that was being polled, not any other devices on the server.  Leaving the device idle for several minutes does not fix the issue.  In current testing, the issue remains until the spark-server process is restarted.

I have not noticed any related events in the server console yet.

Please let me know if I can provide any additional information or testing to help diagnose this.

**Comment by wdimmit** [comment]
The console log for the server appears as follows at the point of failure.  The upper request worked, the lower request did not.

` ::ffff:67.161.118.40 - - [03/Jan/2017:20:23:37 +0000] "GET /v1/devices/310023000647343432313031/randomSmall?access_token=23ebff850ac11f2ebf20d8683a04a6934ad3f289 HTTP/1.1" 200 13 "-" "curl/7.47.0"
 GetVar { deviceID: '310023000647343432313031' }
 ::ffff:67.161.118.40 - - [03/Jan/2017:20:23:38 +0000] "GET /v1/devices/310023000647343432313031/randomSmall?access_token=23ebff850ac11f2ebf20d8683a04a6934ad3f289 HTTP/1.1" 400 58 "-" "curl/7.47.0"
GetVar { deviceID: '310023000647343432313031' }
`

**Comment by jlkalberer** [comment]
@wdimmit - thanks, we'll look into this.  When I moved the code over I only tested functions and not variables. We should get a fix out by Thursday.

**Comment by wdimmit** [comment]
@jlkalberer For what it's worth, this error state seems to block access to functions as variables once it is triggered.

**Comment by wdimmit** [comment]
One last detail:  This happens with function calls as well.  Error message is the same.  Log snippet of the break between the last good request and the first bad request follows.

`FunCall { deviceID: '1c0036001947343433313339' }

TODO: Type buildArguments

Pinged, replying { deviceID: '1c0036001947343433313339' }

::ffff:67.161.118.40 - - [03/Jan/2017:20:51:47 +0000] "POST /v1/devices/1c0036001947343433313339/arioSet HTTP/1.1" 200 285 "-" "curl/7.47.0"

FunCall { deviceID: '1c0036001947343433313339' }

TODO: Type buildArguments

::ffff:67.161.118.40 - - [03/Jan/2017:20:51:48 +0000] "POST /v1/devices/1c0036001947343433313339/arioSet HTTP/1.1" 400 58 "-" "curl/7.47.0"`

**Comment by jlkalberer** [comment]
@AntonPuko - I think this might be the culprit.  https://github.com/Brewskey/spark-protocol/blob/master/src/clients/Device.js#L625-L635

I don't think it should reject there.  @wdimmit you can validate by turning on `showVerboseDeviceLogs` in spark-protocol.

**Comment by wdimmit** [comment]
Setting that flag to true in /src/settings.js had no impact on the console log output.  Also tried setting "verboseProtocol: true", but that had no impact either.

**Comment by jlkalberer** [comment]
@wdimmit - Is this your test firmware? Do you mind making a gist for @AntonPuko to test with?

**Comment by jlkalberer** [comment]
Also, are you doing multiple requests for multiple devices or just a single device?

**Comment by wdimmit** [comment]
I'm doing 1 request / second for a single device, with no other activity against the API.  Gist here: https://gist.github.com/wdimmit/0b9a86f5f0ccf212f22fdc51601c3e45

Thanks.

**Comment by jlkalberer** [comment]
Ok, one more thing to check. Have you manually removed the `spark-protocol` from your `spark-server` npm modules and done another install? NPM isn't smart enough to know that a git repo has been updated :/

**Comment by AntonPuko** [comment]
hm..can't reproduce none of your issues:
requests work fine:
![varrequests](https://cloud.githubusercontent.com/assets/8849922/21625229/53905e22-d213-11e6-915f-d3175dcf3335.png)
and string vars, too:
![123strings](https://cloud.githubusercontent.com/assets/8849922/21625236/5f87c8e6-d213-11e6-92e5-22ad54664a69.png)

**Comment by wdimmit** [comment]
I didn't realized that a copy was being cached in node_modules.... My mistake.  This voids my observation about those settings variables not changing anything.

This fixes the string variable issue.  I'm re-investigating the failure after a number of requests issue.

**Comment by jlkalberer** [comment]
@wdimmit - yeah, that's why on our dev machines we are using `npm link` and running watchman on the `spark-protocol` folder. It makes testing a whole lot easier.

**Comment by wdimmit** [comment]
I'm still seeing the read failure.  It often takes several minutes to occur, so 50 iterations will not be sure to trigger it.  My last test took roughly 5 minutes to start failing.  

I've enabled both the verbosity settings options in spark-protocol (specifically in ./node_modules/spark-protocol/src/settings.js) and I'm still not seeing anything extra in the console surrounding the failure.

**Comment by AntonPuko** [comment]
Well, I reproduced your requests issue. seems it something about message's token counter, which at some point becomes bigger than allowed in a device. I'll dig into it tomorrow.

**Comment by wdimmit** [comment]
@AntonPuko Glad you've seen it.  If it helps, the magic number seems to be 250 +/- 5.  Timing of the requests doesn't seem to matter.  Thanks.

**Comment by AntonPuko** [comment]
ye, noticed that also seems counter breaks when its more than one byte

**Comment by jlkalberer** [comment]
Ahh, that makes sense.  It can be fixed [here](https://github.com/Brewskey/spark-protocol/blob/master/src/clients/Device.js#L475-L480)

For tokens it must be less than 256
https://github.com/straccio/spark-protocol/blob/master/clients/SparkCore.js#L547-L570

Here is what it's supposed to be:
https://github.com/straccio/spark-protocol/blob/master/settings.js#L35-L44

**Comment by jlkalberer** [comment]
Alright,  fix is out.  I haven't tested as I don't have a device set up but I'm pretty sure we should be good to go after this: https://github.com/Brewskey/spark-protocol/commit/4afd37f5837f975516a02e3ff8b81dd33f61d4a1

**Comment by wdimmit** [comment]
It appears the previous commit to spark-protocol (pull request #19....) broke something related to variable reads.  All queries return the following, and the pull request in question impacted this area of the code:

{
  "error": "device.onApiMessage is not a function",
  "ok": false
}

**Comment by AntonPuko** [comment]
@wdimmit that pull has some breaking changes and intended to be in pair with https://github.com/Brewskey/spark-server/pull/60.
@jlkalberer we probably need to make `dev` branch in spark-protocol.

**Comment by jlkalberer** [comment]
Yeah, makes sense since people are starting to use this.  I'll create a branch.
